apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-system
  template:
    metadata:
      labels:
        app: banking-system
    spec:
      containers:
        - name: banking-system
          image: banking-system:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: banking-system-svc
spec:
  type: NodePort
  selector:
    app: banking-system
  ports:
    - port: 8080
      targetPort: 8080
