name: Java CI/CD - Banking System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: 🔨 Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
        working-directory: BankingSystem

  test:
    name: ✅ Run JUnit Tests
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test
        working-directory: BankingSystem

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: BankingSystem/target/surefire-reports/

  deploy:
    name: 🚀 Deploy BankingSystem to Minikube
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack curl apt-transport-https socat

      - name: Install kubectl
        run: |
          echo "Downloading latest stable kubectl version..."
          KUBECTL_VERSION=$(curl -Ls https://dl.k8s.io/release/stable.txt)
          echo "Version is $KUBECTL_VERSION"
          curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          sudo minikube start --driver=docker
          kubectl get nodes

      - name: Build Docker image for BankingSystem
        run: |
          eval $(minikube docker-env)
          docker build -t banking-system:latest BankingSystem/

      - name: Deploy BankingSystem to Minikube
        run: |
          kubectl create deployment banking-system --image=banking-system:latest
          kubectl expose deployment banking-system --type=NodePort --port=8080
          sleep 10  # wait for pod to start
          kubectl get all

      - name: Simulate Access to App
        run: |
          minikube service banking-system --url || true

      - name: Confirm Deployment
        run: echo "✅ BankingSystem deployed to Minikube!"
