name: Java CI/CD - Banking System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: 🔨 Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
        working-directory: BankingSystem

  test:
    name: ✅ Run JUnit Tests
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test
        working-directory: BankingSystem

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: BankingSystem/target/surefire-reports/

  deploy:
    name: 🚀 Simulate Deployment with Minikube
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack curl apt-transport-https

      - name: Install kubectl
        run: |
             KUBECTL_VERSION=$(curl -s https://dl.k8s.io/release/stable.txt)
             curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
             chmod +x kubectl
             sudo mv kubectl /usr/local/bin/


      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          kubectl get nodes

      - name: Deploy Sample Java App (Echo Server)
        run: |
          kubectl create deployment hello-java-app --image=kicbase/echo-server:1.0
          kubectl expose deployment hello-java-app --type=NodePort --port=8080
          kubectl get services

      - name: Simulate Access to App
        run: |
          minikube service hello-java-app --url

      - name: Confirm Deployment
        run: echo "✅ Sample app deployed to Minikube!"
