name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
        working-directory: BankingSystem

      - name: Run tests
        run: mvn test
        working-directory: BankingSystem

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          echo "Deploying artifact..."
          ls BankingSystem/target/
          # Example deployment: copy JAR to server
          # scp BankingSystem/target/*.jar user@yourserver:/deploy/path

